services:
  http-server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    networks:
      - local-network
    depends_on:
      - mysql
    volumes:
      - ./server:/app

  mysql:
    image: mysql:8.0.31
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: esp_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Jakarta
    command: ['mysqld', '--default-time-zone=+07:00']
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - local-network

networks:
  local-network:
    driver: bridge